### ISSUE TITLE
Installation not working on macOS Catalina 10.15.3

### ISSUE THREAD

**Issue by gammaeva** [Cytomine-ULiege/Cytomine-bootstrap#10]
Hello,

I'm having some problems installing Cytomine on macOS Catalina. When I execute the init.sh I have this error message :  
`sed: 1: "/-v \/data\/certificate ...": command c expects \ followed by text`

I think it comes from this line :  

` sed -i '' -e "/-v ${CERTIFICATE_PATH//\//\\/}:/certificates/d" $I;`

Could you please let me know how to fix this issue?

**Comment by geektortoise** [comment]
Should be fixed by 
8b7677f71b0df71af2ca826f7e19ac31d5ba6fb4
