### ISSUE TITLE
Wrong POSTGRES_ALIAS name

### ISSUE THREAD

**Issue by buzzfrog** [Cytomine-ULiege/Cytomine-bootstrap#4]
Hi
I think that you have a miss match regarding the name of the postgresql docker container.
In init.sh, row 25 it is **POSTGRES_ALIAS=postgres** but in start.sh.sample.sh the name of the container is postgresql, see row 91.

Core will not find the posgresql container because of this.

**Comment by urubens** [comment]
Thanks, good catch ! Fixed in 0e6b2bcc722b17dcf6244303c382ccb86c38533f
