### ISSUE TITLE
Unable to inject demo data

### ISSUE THREAD

**Issue by illeb** [Cytomine-ULiege/Cytomine-bootstrap#5]
Hello,

following the instructions listed on https://doc.cytomine.be/display/PubOp/Install+Cytomine+on+Linux i am unable to inject demo data inside my local installation of cytomine, with the following error message:

```
root@debian:/home/lux/Cytomine/Cytomine-bootstrap# bash inject_demo_data.sh
Unable to find image 'cytomine/data_for_test:latest' locally
docker: Error response from daemon: pull access denied for cytomine/data_for_test, repository does not exist or may require 'docker login'.
See 'docker run --help'.
Error: No such container: data_for_test
Error: No such container: data_for_test
```
What i am doing wrong?
I am using a fresh installation of Debian 9.

Thanks

**Comment by urubens** [comment]
The script to inject sample projects was completely broken, thanks for reporting it.
I updated the repo with a brand new project injector.

I suggest you to
1. Be sure that you changed the admin password (Account in the top right in the web interface)
2. Update your Cytomine-bootstrap with last commits
3. Run `inject_demo_data.sh ADMIN_PUBLIC_KEY ADMIN_PRIVATE_KEY` where the `ADMIN_*_KEY` have to be replaced by the keys of admin user (available in the Account page in the web interface).

By default, it will add the Cytomine projects that you can find in [this repo](https://github.com/Cytomine-ULiege/Cytomine-sample-projects). It should take less than 10 minutes, but it depends on your network connection.

**Comment by illeb** [comment]
The demo data now finally injects painlessly, many thanks.
However, i am still unable to find the Algorithms showed in the demo istance of Cytomine (https://demo.cytomine.be/#software) and use it for my classification purposes.

I am missing something to include those softwares in my local cytomine istance?
